### ISSUE TITLE
Missing typings for "axios-retry" property for request-specific configuration

### ISSUE THREAD

**Issue by Jokero** [softonic/axios-retry#147] opened 2020-07-30 17:29 UTC
There is the following example in the documentation that demonstrates the usage of request-specific retry options:
```
// Allows request-specific configuration
client
  .get('/test', {
    'axios-retry': {
      retries: 0
    }
  })
  .catch(error => { // The first request fails
    error !== undefined
  });
```
However currently it's not possible to use that code in Typescript as `AxiosRequestConfig` does not know anything about `axios-retry` property:
```
error TS2345: Argument of type '{ 'axios-retry': { retries: number; }; }' is not assignable to parameter of type 'AxiosRequestConfig'.
  Object literal may only specify known properties, and ''axios-retry'' does not exist in type 'AxiosRequestConfig'.

10         'axios-retry': {
           ~~~~~~~~~~~~~~~~
11             retries: 0
   ~~~~~~~~~~~~~~~~~~~~~~
12         }
   ~~~~~~~~~

```
To fix that this should be added to typings:
```
declare module 'axios' {
    export interface AxiosRequestConfig {
        'axios-retry': IAxiosRetryConfig;
    }
}
```

**Comment by mawrkus** [comment] 2020-08-19 13:09
Looks like a duplicate of #136 would you be willing to open a PR for this? Would be highly appreciated!

**Comment by Jokero** [comment] 2020-09-16 11:35
@mawrkus Yeah, I will prepare PR

**Comment by mawrkus** [comment] 2020-09-18 05:36
Nice, thanks!

**Closed** 2020-09-18 05:36 UTC
Labels: duplicate
