### ISSUE TITLE
bug?: retry not working

### ISSUE THREAD

**Issue by roachadam** [softonic/axios-retry#161] opened 2021-02-02 06:29 UTC
Not quite sure how this happened, but I'm probably missing something stupid.

Code:
```js
axiosRetry(this.ax, { 
	retries: 3,
	retryCondition: (e) => {
		//return true;
		if(!e.response)
			return false;

		//todo 302
		return e.response.status >=200 && e.response.status <=204;
	}
});
```
For whatever reason, I make a request with that same ax instance, get a 502 error, and it does not retry. I also uncommented the return true, and it still does not retry.

I thought it could be interfering with my other axios interceptor, but I turned that off and still the same issue persists.

win64 bit
node v12.16.1
axios-retry v

**Comment by ffxsam** [comment] 2021-04-27 21:20
Same here, non-working right out of the box. Pretty basic test, and I never see my `console.log` statement:

```js
const axios = require('axios');
const axiosRetry = require('axios-retry');

axiosRetry(axios, {
  retries: 3,
  retryDelay: retryCount => {
    console.log('retry count:', retryCount);
    return retryCount * 1000;
  }
});

(async function() {
  const data = await axios.get('http://httpstat.us/503');
})();
```

**Comment by schmidlidev** [comment] 2021-12-03 18:58
This library seems to just... not work? I even tried:

> retryCondition: () => true

and could not get this library to ever perform a retry.
Ended up using https://www.npmjs.com/package/retry-axios instead.

**Comment by geoffrich** [comment] 2021-12-09 18:29
I ran into this issue, and for me it was caused by my Axios version. 0.21.2 introduced a bug that [0.21.3](https://github.com/axios/axios/blob/master/CHANGELOG.md#0213-september-4-2021) fixed. Updating Axios caused the retries to succeed.

That likely isn't the cause of OP's issue, since they created this issue in February and 0.21.2 was released in September, but wanted to comment in case someone else had the same root cause.

**Comment by JSEvgeny** [comment] 2022-02-03 14:38
Doesn't work with `axios: 0.21.1` neither

**Closed** 2022-05-20 18:18 UTC
