### ISSUE TITLE
TypeError [ERR_INVALID_CHAR] when using with axios@1.x

### ISSUE THREAD

**Issue by weeniearms** [softonic/axios-retry#212] opened 2022-10-19 06:30 UTC
When using with the lastest version of axios (1.x) I get the following error:
```
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["0"]
    at ClientRequest.setHeader (node:_http_outgoing:647:3)
    at new ClientRequest (node:_http_client:284:14)
    at Object.request (node:http:97:10)
    at RedirectableRequest._performRequest (/tmp/axiosretry/node_modules/follow-redirects/index.js:284:24)
    at new RedirectableRequest (/tmp/axiosretry/node_modules/follow-redirects/index.js:66:8)
    at Object.request (/tmp/axiosretry/node_modules/follow-redirects/index.js:523:14)
    at dispatchHttpRequest (/tmp/axiosretry/node_modules/axios/dist/node/axios.cjs:2322:21)
    at new Promise (<anonymous>)
    at httpAdapter (/tmp/axiosretry/node_modules/axios/dist/node/axios.cjs:2058:10)
    at Axios.dispatchRequest (/tmp/axiosretry/node_modules/axios/dist/node/axios.cjs:3151:10) {
  code: 'ERR_INVALID_CHAR'
}
```
Steps to reproduce:
1. Run the following server code:
```js
const http = require('http')
const server = http.createServer((req, res) => {
  res.writeHead(500)
  res.end('err')
})
server.listen(8080)
```
2. Execute the following client code:
```js
const axios = require('axios')
const axiosRetry = require('axios-retry')

const client = axios.create()
axiosRetry(client, { retries: 3 })

client.get('http://localhost:8080').catch(err => console.error(err))
```

**Comment by kuizuo** [comment] 2022-10-21 07:06
I also have this situation.

My environment:
- node:  16.15.1
- axios 1.1.3
- axios-retry 3.3.1

**Comment by paulsouche** [comment] 2022-10-21 21:19
Duplicate of #213 There is an opened PR on axios https://github.com/axios/axios/pull/5090

**Comment by mindhells** [comment] 2022-11-02 12:20
I believe based on @paulsouche comment we can close this

**Closed by mindhells** 2022-11-02 12:20 UTC
