### ISSUE TITLE
Custom retry Condition with status 200?

### ISSUE THREAD

**Issue by GsHeri** [softonic/axios-retry#117] opened 2020-04-03 16:31 UTC
so i thought i could override the retry condition, but seems i was wrong.
it works fine when i request a source that is not reachable.
but if i poll a media service and wait for a file to be processed (which returns 200 with "state: 'processing'" or "state: 'processed'" 
this library seems to not react at all on a 200...?

```
const client = axios.create()
          axiosRetry(client, {
            retries: 3,
            retryCondition: res => res.data.state !== 'processed',
            retryDelay: axiosRetry.exponentialDelay,
          })
```
i've tried many different ways of writing that function, but it's just never even called on a 200....
why? how can i fix it?

**Comment by mawrkus** [comment] 2020-04-18 18:27
Hi, seems your question is a duplicate of https://github.com/softonic/axios-retry/issues/100

**Closed by mawrkus** 2020-04-18 18:27 UTC
Labels: duplicate
